<a href="https://colab.research.google.com/github/jaewon00o0/kbu-2.1/blob/main/2026_03_27%EC%88%98%EC%97%85%EB%82%B4%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
4.네이버와_구글의_서버_헤더_정보_비교하기

In [1]:
import requests

In [2]:
res_naver = requests.get("https://www.naver.com")
res_google = requests.get("https://www.google.com")

In [3]:
print(f"Server: {res_naver.headers.get('Server')}")
print(f"Date: {res_naver.headers.get('Date')}")

Server: nfront
Date: Fri, 27 Mar 2026 04:54:25 GMT

In [4]:
print(f"Server: {res_google.headers.get('Server')}")
print(f"Date: {res_google.headers.get('Date')}")

Server: gws
Date: Fri, 27 Mar 2026 04:54:25 GMT

In [5]:
print("\n[네이버 전체 헤더]\n", res_naver.headers)
print("\n[구글 전체 헤더]\n", res_google.headers)

[네이버 전체 헤더]
 {'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'x-frame-options': 'DENY', 'x-xss-protection': '1; mode=block', 'strict-transport-security': 'max-age=63072000; includeSubdomains', 'referrer-policy': 'unsafe-url', 'Content-Encoding': 'gzip', 'Server': 'nfront', 'Content-Length': '28722', 'Date': 'Fri, 27 Mar 2026 04:54:25 GMT', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding'}

[구글 전체 헤더]
 {'Date': 'Fri, 27 Mar 2026 04:54:25 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=ISO-8859-1', 'Content-Security-Policy-Report-Only': "object-src 'none';base-uri 'self';script-src 'nonce-855RQadO3VdJOLerz1MoDg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp", 'Reporting-Endpoints': 'default="//www.google.com/httpservice/retry/jserror?ei=gQ3Gae6NFenIkPIPzbWUqQ4&cad=crash&error=Page%20Crash&jsel=1&bver=2410&dpf=pOKNsrH-QxHTdY5W4FtYXgul4D-A7c4z6GcDvBHY9M4"', 'Accept-CH': 'Sec-CH-Prefers-Color-Scheme', 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': '__Secure-STRP=AEEP7gKAGsiJsmfljLMRBYc6y9qQb6hi0Pt9Sb8Ir_ljBpOUWm3cE25ci-rJFLfjGDnt0Jv_GdENa5OzQOt39vOEG_rsMy4xHA55; expires=Fri, 27-Mar-2026 04:59:25 GMT; path=/; domain=.google.com; Secure; SameSite=strict, AEC=AaJma5u43VGfhxiFVBWNNYl3RDhA4ipvM1IgDjUFla1Ql6-rb2Y1JqwWT0A; expires=Wed, 23-Sep-2026 04:54:25 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=530=RkCS11iGzjeyetcKXO9ZeB_MzmMEbuOcIabPC4j8-UlmHMqPkVuD3BL0K_oa1_s8hLtZaqJD_iRP1DlNKW9NZqQIPJ_8KG-f-QRd7rMcGAYivc0hbPRbcsKvspsHZB9iprpr2uhXiSoFdn0QwkFqFUVrTWiEusBL0mhnsP-1qH6ZATAD77ET73RYklsNanbYSKWGFjp3i7vMqNfwxwNovlRajdfILWLO2WbT; expires=Sat, 26-Sep-2026 04:54:25 GMT; path=/; domain=.google.com; HttpOnly, __Secure-BUCKET=CCU; expires=Wed, 23-Sep-2026 04:54:25 GMT; path=/; domain=.google.com; Secure; HttpOnly', 'Transfer-Encoding': 'chunked'}

In [6]:
5. url = "https://jsonplaceholder.typicode.com/users" 에서 requests 모듈로 json파일로
불러와 데이터프레임으로 저장하고 컬럼명(변수명)이 “address”인 series의 내용을
데이터프레임으로 변경하라

SyntaxError: invalid character '“' (U+201C) (607277357.py, line 2)

In [7]:
import requests
import pandas as pd
from IPython.display import display

In [8]:
url = "https://jsonplaceholder.typicode.com/users"

In [9]:
response = requests.get(url)
data = response.json()

In [10]:
df = pd.DataFrame(data)

In [11]:
address_df = pd.json_normalize(df['address'])

In [12]:
display(df)
display(address_df)

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

,street,suite,city,zipcode,geo.lat,geo.lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342
5,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478
6,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984
7,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677
8,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889
9,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232

In [13]:
6. url = "https://jsonplaceholder.typicode.com/posts" 에서 데이터를 불러와 index가
짝수인 내용만 엑셀로 저장하여 다운로드 받아라

SyntaxError: invalid syntax (614665103.py, line 1)

In [14]:
import requests
import pandas as pd

In [15]:
response = requests.get(url)
data = response.json()

In [16]:
df = pd.DataFrame(data)

In [17]:
even_df = df[df.index % 2 == 0]

In [18]:
file_name = "even_posts.xlsx"
even_df.to_excel(file_name, index=False)

In [19]:
from google.colab import files
files.download(file_name)

In [20]:
7.url = "https://jsonplaceholder.typicode.com/posts"에서 데이터를 불러와
requests.get(url, params=params)를 사용하여 사용자가 Gradio UI를 통해 userId를
입력하면 실시간으로 해당 데이터를 필터링하여 Pandas 데이터프레임으로 보여주는
코드를 작성하라

SyntaxError: invalid decimal literal (513429342.py, line 1)

In [40]:
import requests
import pandas as pd
import gradio as gr
from google.colab import ai

In [22]:
def get_user_posts(user_id):
    if not user_id or user_id <= 0:
        return pd.DataFrame()
    url = "https://jsonplaceholder.typicode.com/posts"
    params = {'userId': int(user_id)}
    data = requests.get(url, params=params).json()
    return pd.DataFrame(data)

In [25]:
url = "https://jsonplaceholder.typicode.com/posts"

In [30]:
params = {'userId': int(user_id)}

In [34]:
data = requests.get(url, params=params).json()

In [39]:
ui = gr.Interface(
    fn=fetch_and_translate,
    inputs=gr.Number(label="userId를 입력하세요 (예: 1, 2)", precision=0),
    outputs=[
        gr.Dataframe(label="검색된 포스트 목록"),
        gr.Textbox(label="원본 텍스트"),
        gr.Textbox(label="번역된 텍스트")
    ],
    title="실시간 포스트 검색기 및 번역기",
    live=True
)

In [41]:
ui.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://5474342f16f5e6145e.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
8. https://data.seoul.go.kr/dataList/OA-15246/F/1/datasetView.do# 3개월
데이터(서울특별시 공공자전거 이용정보(일별)_2510.csv, 서울특별시 공공자전거
이용정보(일별)_2511.csv, 서울특별시 공공자전거 이용정보(일별)_2512.csv)를 다운받아
merge하여 기본 통계분석 사이트를 gradio UI로 만들어라

In [42]:
pip install pandas gradio plotly

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.12.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.135.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.7.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.0)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.6)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.42.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [44]:
import pandas as pd
import gradio as gr
import plotly.express as px
from google.colab import ai

In [49]:
def load_data():
    file_names = [
        '서울특별시 공공자전거 이용정보(일별)_2510.csv',
        '서울특별시 공공자전거 이용정보(일별)_2511.csv',
        '서울특별시 공공자전거 이용정보(일별)_2512.csv'
    ]

    df_list = []
    for file in file_names:
        try:
            df = pd.read_csv(file, encoding='cp949')
            df_list.append(df)
        except FileNotFoundError:
            print(f"경고: '{file}' 파일을 찾을 수 없습니다. 파일명을 확인해주세요.")
            continue
        except UnicodeDecodeError:
            # cp949로 안될 경우 utf-8 시도
            try:
                df = pd.read_csv(file, encoding='utf-8')
                df_list.append(df)
            except Exception as e:
                print(f"경고: '{file}' 파일을 utf-8로 읽는 중 오류 발생: {e}")
                continue

    if not df_list:
        return pd.DataFrame()

    merged_df = pd.concat(df_list, ignore_index=True)

    if '대여일자' in merged_df.columns:
        merged_df['대여일자'] = pd.to_datetime(merged_df['대여일자'], errors='coerce'
    if '이용건수' in merged_df.columns:
        merged_df['이용건수'] = pd.to_numeric(merged_df['이용건수'], errors='coerce').fillna(0)

    return merged_df

In [47]:
df = load_data()

경고: '서울특별시 공공자전거 이용정보(일별)_2510.csv' 파일을 찾을 수 없습니다. 파일명을 확인해주세요.

In [54]:
df = load_data()

def get_summary_stats():
    if df is None or df.empty:
        return "데이터를 불러오지 못했습니다. CSV 파일 위치를 확인하세요."

    total_records = len(df)
    total_usage = df['이용건수'].sum() if '이용건수' in df.columns else "N/A"
    date_range = f"{df['대여일자'].min().date()} ~ {df['대여일자'].max().date()}" if '대여일자' in df.columns else "N/A"

    summary = f"""
    ###  데이터 병합 요약
    * **총 데이터 건수:** {total_records:,} 건
    * **총 이용 건수:** {total_usage:,} 건
    * **데이터 수집 기간:** {date_range}
    """
    return summary

경고: '서울특별시 공공자전거 이용정보(일별)_2510.csv' 파일을 찾을 수 없습니다. 파일명을 확인해주세요.
경고: '서울특별시 공공자전거 이용정보(일별)_2511.csv' 파일을 찾을 수 없습니다. 파일명을 확인해주세요.
경고: '서울특별시 공공자전거 이용정보(일별)_2512.csv' 파일을 찾을 수 없습니다. 파일명을 확인해주세요.

In [58]:
def plot_daily_trend():
    if df is None or df.empty or '대여일자' not in df.columns or '이용건수' not in df.columns:
        return None

    daily_df = df.groupby('대여일자')['이용건수'].sum().reset_index()
    fig = px.line(daily_df, x='대여일자', y='이용건수', title=' 일별 공공자전거 총 이용건수 추이')
    return fig

In [67]:
def plot_age_gender_stats():
    if df is None or df.empty:
        return None, None

    fig1 = None
    if '연령대코드' in df.columns and '이용건수' in df.columns:
        age_df = df.groupby('연령대코드')['이용건수'].sum().reset_index()
        fig1 = px.bar(age_df, x='연령대코드', y='이용건수', title=' 연령대별 누적 이용건수', color='연령대코드')

    fig2 = None
    if '성별' in df.columns and '이용건수' in df.columns:
        gender_df = df.groupby('성별')['이용건수'].sum().reset_index()
        fig2 = px.pie(gender_df, names='성별', values='이용건수', title=' 성별 이용 비율')

    return fig1, fig2

In [72]:
with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("# 서울특별시 공공자전거(따릉이) 3개월 분석 대시보드")
    gr.Markdown("3개의 월별 CSV 데이터를 병합하여 만든 기본 통계분석 사이트입니다.")

    if df is None or df.empty:
        gr.Markdown("###  에러: CSV 파일 데이터를 불러오지 못했습니다. 코드가 있는 폴더에 파일이 있는지 확인해주세요.")
    else:
        with gr.Tabs():
            with gr.TabItem(" 기본 요약 및 데이터"):
                summary_output = gr.Markdown(get_summary_stats())
                gr.Markdown("###  병합된 데이터 미리보기 (상위 100개)")
                gr.Dataframe(df.head(100), interactive=False)

            with gr.TabItem(" 일별 이용 추이"):
                trend_plot = gr.Plot(plot_daily_trend())

            with gr.TabItem(" 연령/성별 분석"):
                with gr.Row():
                    age_plot = gr.Plot()
                    gender_plot = gr.Plot()
                app.load(plot_age_gender_stats, outputs=[age_plot, gender_plot])

    app.launch(share=False)

/tmp/ipykernel_2432/533799789.py:1: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(theme=gr.themes.Soft()) as app:

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.
* To create a public link, set `share=True` in `launch()`.

In [77]:

a. 7번과제를 번역하여 제공해주는 UI를 만들어라

SyntaxError: invalid syntax (3285949243.py, line 1)

In [78]:
!pip install gradio pandas requests

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.12.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.135.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.7.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.0)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.6)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.42.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [79]:
import requests
import pandas as pd
import gradio as gr
from google.colab import ai

In [83]:
def fetch_and_translate(user_id):
    url = "https://jsonplaceholder.typicode.com/posts"

    params = {'userId': int(user_id)} if user_id else {}
    translated_text = "번역할 내용이 없습니다."
    original_text_display = ""

    try:
        response = requests.get(url, params=params)
        data = response.json()
        df = pd.DataFrame(data)
    except Exception as e:
        return pd.DataFrame(), f"데이터 호출 에러: {e}", translated_text

    if df.empty:
        return df, "해당 userId의 데이터가 없습니다.", translated_text

    first_row = df.iloc[0]
    original_text_display = f"Title: {first_row['title']}\nBody: {first_row['body']}"

    prompt = f"다음 영어 문장을 한국어로 자연스럽게 번역해줘:\n{original_text_display}"
    try:
        ai_response = ai.generate_text(prompt)
        translated_text = ai_response.text if hasattr(ai_response, 'text') else str(ai_response)
    except Exception as e:
        translated_text = f"번역 중 오류가 발생했습니다.\n코랩 환경인지 확인해주세요: {e}"

    return df, original_text_display, translated_text

In [81]:
with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("##  게시글 실시간 필터링 및 1행 AI 번역기")
    gr.Markdown("7번 과제(userId 필터링)와 9번 과제(첫 행 번역)를 통합한 화면입니다.")

/tmp/ipykernel_2432/4294966568.py:1: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(theme=gr.themes.Soft()) as app:

In [85]:
with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("## 게시글 실시간 필터링 및 1행 AI 번역기")
    gr.Markdown("7번 과제(userId 필터링)와 9번 과제(첫 행 번역)를 통합한 화면입니다.")

    with gr.Row():
        user_id_input = gr.Number(label="User ID 입력", value=1, precision=0)

    with gr.Row():
        df_output = gr.Dataframe(label="필터링된 데이터프레임", interactive=False)

    gr.Markdown("### 첫 번째 행(1행) 번역 결과 (9번 과제 - Colab AI)")
    with gr.Row():
        original_output = gr.Textbox(label="원본 텍스트 (1행)", lines=5, interactive=False)
        translated_output = gr.Textbox(label="한국어 번역", lines=5, interactive=False)

    user_id_input.change(
        fn=fetch_and_translate,
        inputs=user_id_input,
        outputs=[df_output, original_output, translated_output],
    )

    app.launch(debug=True)

/tmp/ipykernel_2432/323867527.py:1: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(theme=gr.themes.Soft()) as app:

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://d85a5750aa82c3363b.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://5474342f16f5e6145e.gradio.live
Killing tunnel 127.0.0.1:7862 <> https://d85a5750aa82c3363b.gradio.live

In [ ]:
app.launch(debug=True)

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://7eef669bb84764ba2c.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
10. https://huggingface.co/ 를 클릭하여 멀티모달 LLM을 사용해 보자

In [86]:
!pip install gradio requests

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.12.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.135.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.7.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.0)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.6)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.42.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [87]:
import gradio as gr
import requests

In [88]:
API_URL = "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-large"

In [90]:
def analyze_image_with_hf(image_filepath):
    """
    업로드된 이미지를 Hugging Face API로 보내서 분석 결과를 받아오는 함수
    """
    if image_filepath is None:
        return "이미지를 업로드해주세요."

    try:
        with open(image_filepath, "rb") as f:
            data = f.read()

        response = requests.post(API_URL, data=data)
        result = response.json()

        if isinstance(result, list) and 'generated_text' in result[0]:
            return result[0]['generated_text']
        elif 'error' in result:
            return f"API 로딩 중입니다. 잠시 후 다시 시도해주세요. (에러: {result['error']})"
        else:
            return str(result)

    except Exception as e:
        return f"분석 중 오류가 발생했습니다: {e}"

In [94]:
with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("##  10번 과제: Hugging Face 멀티모달 LLM 테스트")
    gr.Markdown("Hugging Face의 `BLIP` 모델을 활용하여, 업로드한 이미지를 AI가 분석하고 상황을 설명(Captioning)해 줍니다.")

    with gr.Row():
        with gr.Column():
            gr.Markdown("###  이미지 업로드")
            image_input = gr.Image(type="filepath", label="분석할 이미지를 올려주세요")
            analyze_btn = gr.Button(" AI에게 이미지 분석 요청하기", variant="primary")

        with gr.Column():
            gr.Markdown("###  AI의 이미지 분석 결과 (영어)")
            output_text = gr.Textbox(label="Generated Caption", lines=4, interactive=False)

    analyze_btn.click(
        fn=analyze_image_with_hf,
        inputs=image_input,
        outputs=output_text
    )

    app.launch(debug=True)

/tmp/ipykernel_2432/3137921820.py:1: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(theme=gr.themes.Soft()) as app:

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://71a299eec291f22d23.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7862 <> https://71a299eec291f22d23.gradio.live